### ISSUE TITLE
Conda Env create fails on fraggenescan

### ISSUE THREAD

**Issue by bstamps** [pnnl/atlas#1]
Having an issue with installing ATLAS on an Ubuntu 16.04 server using miniconda. All dependencies install correctly, with the exception of maxbin2. When installing I receive the following error: 

Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...............
Solving package specifications: 

NoPackagesFoundError: Dependency missing in current linux-64 channels: 
  - maxbin2 -> fraggenescan >=1.30 -> perl 5.22.0*

Any help is appreciated!

**Comment by raw937** [comment]
Thank you for using ATLAS. 
Did you try this?
conda install -c brwnj maxbin2

**Comment by bstamps** [comment]
Yes- I'll attempt to re-create this evening to give the specific error but from memory it was still failing on the perl dependency. I forced a workaround by installing fraggenescan separately and then building atlas from the github repo and I'm running the pipe right now.

**Comment by brwnj** [comment]
I fixed the docs. It's likely that you didn't have the conda-forge channel making perl not satisfiable.

Run:

```
conda config --add channels conda-forge
conda config --add channels defaults
conda config --add channels r
conda config --add channels bioconda
```

And then try:

```
conda install maxbin2
```

**Comment by raw937** [comment]
Thanks Joe! bstamps let us know if that works for you?
Once again, thank you for using ATLAS.

**Comment by bstamps** [comment]
Yep, adding the additional channels prior to install fixes the issue. 

Thank you!
