### ISSUE TITLE
diamond database version

### ISSUE THREAD

**Issue by mdjlynch** [pnnl/atlas#10]
Hi. Installed atlas on a new server through conda. I am now getting this error message:

#CPU threads: 12
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Percentage range of top alignment score to report hits: 2
Temporary directory: /tmp
Opening the database...  [0.00483s]
Error: Database was built with a different version of diamond as is incompatible.
Error in job run_diamond_blastp while creating output file cRN5-S40-L001-001/megahit_21_121_20_normalization_k21_t100/functional_annotation/refseq/cRN5-S40-L001-001_hits.tsv.
RuleException:
CalledProcessError in line 672 of /home/mdjlynch/anaconda3/lib/python3.5/site-packages/atlas/rules/assemble.snakefile:
Command ' diamond blastp --threads 12 --outfmt 6 --out cRN5-S40-L001-001/megahit_21_121_20_normalization_k21_t100/functional_annotation/refseq/cRN5-S40-L001-001_hits.tsv                --query cRN5-S40-L001-001/megahit_21_121_20_normalization_k21_t100/functional_annotation/prokka/cRN5-S40-L001-001.faa --db /home/mdjlynch/databases/refseq.dmnd --top 2                --evalue 1e-06 --id 50                --query-cover 60  --gapopen 11                --gapextend 1 --tmpdir /tmp --block-size 2                --index-chunks 4' returned non-zero exit status 1
  File "/home/mdjlynch/anaconda3/lib/python3.5/site-packages/atlas/rules/assemble.snakefile", line 672, in __rule_run_diamond_blastp
  File "/home/mdjlynch/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message

I will rebuild with a current version of diamond to see if that resolves the problem but thought I should post the issue to github. Thanks.

**Comment by brwnj** [comment]
I'll push these FASTAs to Zenodo as well, so we can enable database re-building.

**Comment by brwnj** [comment]
I'll plan the next release to build the reference database and pin external dependencies. I've also pushed the fasta up to a second version of the dataset on Zenodo which is available at:

https://zenodo.org/record/885507

**Comment by mdjlynch** [comment]
Great. Updating seems to have worked. Thanks for the quick turn around.
