### ISSUE TITLE
Error in <get_read_stat> step

### ISSUE THREAD

**Issue by penglbio** [pnnl/atlas#108]
When I follow the steps in the document of atlas:
conda create -n atlas -c bioconda python=3.6 snakemake bbmap=37.78 click ruamel.yaml
source activate atlas
pip install -U pnnl-atlas
atlas download -o ~/databases
atlas make-config --database-dir ~/databases config.yaml  example_data/
atlas assemble config.yaml

I got an error message:
------------------------------------------------------------------------------------------------------------------------
Building DAG of jobs...
RuleException in line 103 of /home/lpeng/software/miniconda3/envs/atlas/lib/python3.6/site-packages/atlas/rules/qc.snakefile:
Could not resolve wildcards in rule get_read_stats:
sample
step
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /var/data/08.metagenome/.snakemake/log/2018-05-22T160919.212775.snakemake.log
---------------------------------------------------------------------------------------------------------------------------------------
I think this is a bug , but I don't know how to resolve it . can you give me some advise

**Comment by SilasK** [comment]
Thank you for using Atlas.

Could you say us which version of snakemake you are using? E.g. snakemake
--version

And may be run atlas as before with the additional commands --debug-dag >>
dag.log and send us the dag.log file. Thank you.

**Comment by penglbio** [comment]
snakemake version 5.1.2

**Comment by SilasK** [comment]
I could reproduce the error. It seems that the error is related to the new
version of snakemeke, which came out this month. The new version of
snakemake require that all the wildcards in output, log, benchmarkfiles are
the same. I can update this until next week probably.

In the mean time you should install atlas as folows.

conda create -n atlas -c bioconda python=3.6 \
    snakemake=4.7 bbmap=37.78 click ruamel.yaml

This shouldn't have any influence on the execution of atlas.
