### ISSUE TITLE
Snakemake>=5.0.0

### ISSUE THREAD

**Issue by brwnj** [pnnl/atlas#116]
I think this should be the minimum version required here https://github.com/pnnl/atlas/blob/master/atlas/Snakefile#L16. Once we mandate that, we should set up groups (https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#defining-groups-for-execution) where appropriate to minimize cluster job submissions.

**Comment by lijiyang** [comment]
5.2.0，5.1.5 (only tested these two versions) have the same problem: https://github.com/pnnl/atlas/issues/118

and 5.1.1 this version can work
