### ISSUE TITLE
Contaminant references not found in config file

### ISSUE THREAD

**Issue by mdehollander** [pnnl/atlas#12]
After creating the config with `altas make-config` the contaminant references are not configured in `config.yaml`:

```
KeyError in line 116 of /home/NIOO.INT/mattiash/lib/python3.6/site-packages/pnnl_atlas-1.0.14-py3.6.egg/atlas/rules/assemble.snakefile:
'contaminant_references'
  File "/home/NIOO.INT/mattiash/lib/python3.6/site-packages/pnnl_atlas-1.0.14-py3.6.egg/atlas/Snakefile", line 186, in <module>
  File "/home/NIOO.INT/mattiash/lib/python3.6/site-packages/pnnl_atlas-1.0.14-py3.6.egg/atlas/rules/assemble.snakefile", line 116, in <module>
```

**Comment by mdehollander** [comment]
A quick edit of the `conf.py` resolved my issue: https://github.com/pnnl/atlas/pull/13 Please review if this is the correct fix.

**Comment by mdehollander** [comment]
Merged with https://github.com/pnnl/atlas/pull/13

**Comment by olchanheski** [comment]
I'm having the same problem, but I can't fix it!

**Comment by brwnj** [comment]
This fix hasn't been pushed to pypi yet, so `pip install pnnl-atlas` is still going to have this issue. Did you install from the master branch?

**Comment by olchanheski** [comment]
Ok, I install from de master and work. Thanks a lot
