### ISSUE TITLE
Multiple paired-end files for the same sample

### ISSUE THREAD

**Issue by mdjlynch** [pnnl/atlas#121]
Can't seem to find reference to this in the documentation. Can you specify multiple files for the same sample in the config file? (e.g., I have reads partitioned across multiple R1/R2 fastq files). I am currently merging the files but was wondering if this could be specified. Thanks.

**Comment by brwnj** [comment]
It's currently not possible, but _could_ be possible. Is this something you run into often?

**Comment by mdjlynch** [comment]
It's encountered somewhat frequently,  but merging the files is an easy
enough solution. Just thought I would confirm. Thanks.

atlas had been a great addition to our workflow.
