### ISSUE TITLE
Infinite runtime with not allowed sample names

### ISSUE THREAD

**Issue by mdehollander** [pnnl/atlas#14]
Just noticed that I had not allowed characters in my sample names. This resulted in snakemake running forever while not doing anything. The sample names in `config.yaml` are auto generated from fastq files with the `make-config` option. They look like: `I16-1253-31-AH34-TACGGTCA-CTCTCTAT-L002-001`
I see in the `README` that only A-Z characters are allowed. When I change to only AZ characters snakemake starts :)
Is there a specific reason not to allow any other characters? It would be nice to see at least a warning when running the config that the sample names are invalid. Or maybe fix it directly, so the automatic creation of the config file works. 
I am happy to contribute if you think this is a good plan.

**Comment by brwnj** [comment]
It's a legacy thing that wasn't taken out though it should have been friendly to dashes. Underscores were originally not allowed.

**Comment by mdehollander** [comment]
All right, got it running with some filtering added to `conf.py`. It would be nice if it wider range of sample names is accepted or corrected when possible. Thanks.

**Comment by brwnj** [comment]
I completely agree! It's something I'm actively debugging and will make changes accordingly.

**Comment by mdehollander** [comment]
Great! I will also keep an eye open while testing to see where to contribute.

**Comment by SilasK** [comment]
When I tested the last time the read names need to contain samplename_R1 and samplename_R2 but no restriction of the samplename. 
Any way it's good to check the config file before running.
