### ISSUE TITLE
Error in assemble

### ISSUE THREAD

**Issue by olchanheski** [pnnl/atlas#17]
When I try make assemble (`atlas assemble ../config.yaml`), I'm having the follow error:

```
5 of 31 steps (16%) done
Error in rule normalize_coverage_across_kmers:
    jobid: 30
    output: testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz
    log: testeverificar/logs/testeverificar_normalization.log

RuleException:
CalledProcessError in line 213 of /home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/rules/assemble.snakefile:
Command ' bbnorm.sh in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz k=21 t=100                interleaved=t minkmers=15 prefilter=t                threads=40 2> testeverificar/logs/testeverificar_normalization.log' returned non-zero exit status 137
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/rules/assemble.snakefile", line 213, in __rule_normalize_coverage_across_kmers
  File "/home/lricardo/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2017-10-02T14:03:40.202404.snakemake.log
Traceback (most recent call last):
  File "/home/lricardo/miniconda3/bin/atlas", line 11, in <module>
    load_entry_point('pnnl-atlas==1.0.15', 'console_scripts', 'atlas')()
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/atlas.py", line 218, in run_assemble
    assemble(os.path.realpath(config), jobs, out_dir, no_conda, dryrun, snakemake_args)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/workflows.py", line 47, in assemble
    check_call(cmd, shell=True)
  File "/home/lricardo/miniconda3/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'snakemake -s /home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/Snakefile -d /home/lricardo/resultados_testecerto -p -j 80 --rerun-incomplete --configfile '/home/lricardo/config.yaml' --nolock --use-conda --config workflow=complete  --' returned non-zero exit status 1
```

**Comment by brwnj** [comment]
What's in `testeverificar/logs/testeverificar_normalization.log`?

**Comment by olchanheski** [comment]
java -ea -Xmx210275m -Xms210275m -cp /home/lricardo/resultados_testecerto/.snakemake/conda/1a775d97/opt/bbmap-37.17/current/ jgi.KmerNormalize bits=32 in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz k=21 t=100 interleaved=t minkmers=15 prefilter=t threads=40
Executing jgi.KmerNormalize [bits=32, in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz, out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz, k=21, t=100, interleaved=t, minkmers=15, prefilter=t, threads=40]

BBNorm version 37.17
Set threads to 100
Set INTERLEAVED to true
Set threads to 40

   ***********   Pass 1   **********   


Settings:
threads:          	40
k:                	21
deterministic:    	true
toss error reads: 	false
passes:           	1
bits per cell:    	16
cells:            	50.11B
hashes:           	3
prefilter bits:   	2
prefilter cells:  	215.85B
prefilter hashes: 	2
base min quality: 	5
kmer min prob:    	0.5

target depth:     	400
min depth:        	3
max depth:        	500
min good kmers:   	15
depth percentile: 	64.8
ignore dupe kmers:	true
fix spikes:       	false

Made prefilter:   	hashes = 2   	 mem = 50.21 GB   	cells = 215.66B   	used = 0.150%
/home/lricardo/resultados_testecerto/.snakemake/conda/1a775d97/bin/bbnorm.sh: linha 169: 39886 Morto                   java -ea -Xmx210275m -Xms210275m -cp /home/lricardo/resultados_testecerto/.snakemake/conda/1a775d97/opt/bbmap-37.17/current/ jgi.KmerNormalize bits=32 in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz k=21 t=100 interleaved=t minkmers=15 prefilter=t threads=40

**Comment by olchanheski** [comment]
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)

**Comment by brwnj** [comment]
From your results directory (or update the file paths), can you try:

```
/home/lricardo/resultados_testecerto/.snakemake/conda/1a775d97/bin/java \
  -ea -Xmx210275m -Xms210275m \
  -cp /home/lricardo/resultados_testecerto/.snakemake/conda/1a775d97/opt/bbmap-37.17/current/ jgi.KmerNormalize \
  bits=32 \
  in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz \
  out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz \
  k=21 t=100 interleaved=t minkmers=15 prefilter=t threads=40
```

I'm curious what the output of this is.

**Comment by olchanheski** [comment]
Executing jgi.KmerNormalize [bits=32, in=testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz, out=testeverificar/sequence_quality_control/testeverificar_04_pe.fastq.gz, k=21, t=100, interleaved=t, minkmers=15, prefilter=t, threads=40]

BBNorm version 37.17
Set threads to 100
Set INTERLEAVED to true
Set threads to 40

   ***********   Pass 1   **********


Settings:
threads:                40
k:                      21
deterministic:          true
toss error reads:       false
passes:                 1
bits per cell:          16
cells:                  50.11B
hashes:                 3
prefilter bits:         2
prefilter cells:        215.85B
prefilter hashes:       2
base min quality:       5
kmer min prob:          0.5

target depth:           400
min depth:              3
max depth:              500
min good kmers:         15
depth percentile:       64.8
ignore dupe kmers:      true
fix spikes:             false

Made prefilter:         hashes = 2       mem = 50.21 GB         cells = 215.66B         used = 0.150%
Morto

**Comment by brwnj** [comment]
Unsure. I like how it just says "dead" at the end.

How big is testeverificar/sequence_quality_control/testeverificar_03_pe.fastq.gz and could you make it available to me if it's of reasonable size to upload?

**Comment by olchanheski** [comment]
testeverificar_03_pe.fastq.gz has 225.242Kb

There is another way to send this to you?

**Comment by brwnj** [comment]
email would work for a file that size, but it may get caught as spam. If you upload to google drive or dropbox or something similar, you can post the share link here.

This issue highlights the lack of working test data. I should get some added to the repository so we can isolate issues related to input files.

**Comment by olchanheski** [comment]
I upload to dropbox.

https://www.dropbox.com/s/2p4i7gi212ob6di/testeverificar_03_pe.fastq.gz?dl=0

**Comment by brwnj** [comment]
I see this is SRR2053281, so I pulled that record (`fastq-dump -M 200 --gzip SRR2053281`) and I'm testing the workflow.

**Comment by olchanheski** [comment]
I test the workflow with another sample (of my work) and I'm having the same error.
I'll try to install in another computer, sometimes is something wrong on my server.

**Comment by brwnj** [comment]
It looks like `bbduk2.sh` is not properly processing interleaved reads. It may depend on sequence identifiers ending with their index (/1 and /2) like:

```
@HWI-ST1035:121:C11C7ACXX:7:1101:18160:2566/1 1:N:0:AGTTCC
ATCCGAGTGCTTCGTTGCATCCGAGGGTTACGTGCGGGGGCCACCCGCACGTAACACTCCGATGGCGTGGCGCTCGACCCGACCGACCCCGCCG
+
BCCFFFFDHGHHHJJJJIJJJIJJJIIDEHGIGICHIGFDBDBBBDDD8B@A?B@CCDCDDDDDDDD0;>-55@DD-<BDB@BD>9@@@BBB@B
@HWI-ST1035:121:C11C7ACXX:7:1101:18160:2566/2 2:N:0:AGTTCC
CGTGCGGCGACCCGTCGGCCCGAAGCGTCGTCAGCGTCGCCAGGTGCCGGTCGGTCACGAAGGCCAGCACGGCGGGG
+
HHHHHJIJJIJJJJHHHFDDDDBDDDDDDDDDDDDDDDDDDBBDCCDCBBBDD@7@BDDDDDDDDB???AB7>BB>B
``` 

As opposed to how reads are formatted in SRAs:

```
@SRR2053281.8468 8468 length=202
AACAAAAAAGCATGGACATTGAATCGTTAAAAGCTTTTAGGACGCGCTTTGATTTACCAGTAAGCGACAAAGAGGTCGAGAGCCTATCATTCTACAAACCACATTTGAAAATGCGCTTAATGCCGGAATTTTTAACGACGTAGTTTTTCTGCGACGTGCTGGTAAGAAACCACCCAGCTCTTTTCTTCGTTCCATCATGTAT
+SRR2053281.8468 8468 length=202
BBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFFFFBBFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFBBBBFFFFFFFFFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@SRR2053281.8470 8470 length=202
AACAAAAAAGGGCTTGGCGGCTCTCTGTTCGGCGTGTCCCGGCTTTGTCCGTCCTTGGCTTACCACCCGTGAGGGCTGTGCTTCGGACTGCCGTGAGTTGCCGAGCCAGATACTCGCAAGCGGAAAGACGCTCTGTAAGTCAGCAAGACCGCCAAGCACGAACTTGGTGGCTCTCTGAAACGCTCCCGCCTCACGGCGGTTC
+SRR2053281.8470 8470 length=202
BBBFFFFFFFFFFIIIIIIIIFIFFFIFIFFIIIFFFFFFBFBFBFFFFFFFF
```

**Comment by olchanheski** [comment]
But I try run another sample:


@MG00HS14:536:C69PWACXX:4:1101:1716:2037 1:N:0:GATCAG
NCCAAACTTTCATATATGTTGCGATTAGCTCTGGGATGTTTAATGTTGTGTTTGTCCAGATACCGTTATTCTTAATAACCAAGTTATCGTTTTCATCTTTT
+
#1=DDFFFHHHHHJJIJJJJJJJJIJIJJIJJJJJJIJCHIIJJIHIJEIIJJJIJJGGIJJJJIGHIEHGH>AE@DEEFFDECEEEDBDDDDDDEEDDDD
@MG00HS14:536:C69PWACXX:4:1101:1720:2098 1:N:0:GATCAG
TTCGTTGGGAGAGAGAATAACGGTGGCGACTTCTGGAATTACTCCAGCTTGGAGACTTTGATAATCGCTAACACCAGCATCGAGGAAAACTACGGTAGCGG
+
CCCFFFFFHFHHHJJJIJJJIJI?FEIIJIJIJJJIGIGIGIIJHGGHGHJFCGAEHHHGEFBDFDDCDCDDDDD?ABDDDBDDDDDDDD@CD@>989>@B
@MG00HS14:536:C69PWACXX:4:1101:1584:2166 1:N:0:GATCAG
CTTCAGAGAGGTGTAACCGACGTTCGAGCCGTGCAGGTTCTGCGCGGCATAGAGTTCGATGGCCTTGTCCCAACTGCCCGCCGTGCGCAGCGCTCGCGCCT
 

that looks like your first example.

Using this sample I have the follow error:


5 of 31 steps (16%) done

rule normalize_coverage_across_kmers:
    input: TIETE25-R3/sequence_quality_control/TIETE25-R3_03_pe.fastq.gz
    output: TIETE25-R3/sequence_quality_control/TIETE25-R3_04_pe.fastq.gz
    log: TIETE25-R3/logs/TIETE25-R3_normalization.log
    jobid: 29
    benchmark: logs/benchmarks/normalization/TIETE25-R3.txt
    wildcards: sample=TIETE25-R3
    threads: 40

 bbnorm.sh in=TIETE25-R3/sequence_quality_control/TIETE25-R3_03_pe.fastq.gz out=TIETE25-R3/sequence_quality_control/TIETE25-R3_04_pe.fastq.gz k=21 t=100                interleaved=t minkmers=15 prefilter=t                threads=40 2> TIETE25-R3/logs/TIETE25-R3_normalization.log
Activating conda environment /home/lricardo/resultados_tiete/.snakemake/conda/8cbb0d89.
Error in rule normalize_coverage_across_kmers:
    jobid: 29
    output: TIETE25-R3/sequence_quality_control/TIETE25-R3_04_pe.fastq.gz
    log: TIETE25-R3/logs/TIETE25-R3_normalization.log

RuleException:
CalledProcessError in line 213 of /home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/rules/assemble.snakefile:
Command ' bbnorm.sh in=TIETE25-R3/sequence_quality_control/TIETE25-R3_03_pe.fastq.gz out=TIETE25-R3/sequence_quality_control/TIETE25-R3_04_pe.fastq.gz k=21 t=100                interleaved=t minkmers=15 prefilter=t                threads=40 2> TIETE25-R3/logs/TIETE25-R3_normalization.log' returned non-zero exit status 137
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/rules/assemble.snakefile", line 213, in __rule_normalize_coverage_across_kmers
  File "/home/lricardo/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2017-10-03T12:25:19.256711.snakemake.log
Traceback (most recent call last):
  File "/home/lricardo/miniconda3/bin/atlas", line 11, in <module>
    load_entry_point('pnnl-atlas==1.0.15', 'console_scripts', 'atlas')()
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/atlas.py", line 218, in run_assemble
    assemble(os.path.realpath(config), jobs, out_dir, no_conda, dryrun, snakemake_args)
  File "/home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/workflows.py", line 47, in assemble
    check_call(cmd, shell=True)
  File "/home/lricardo/miniconda3/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'snakemake -s /home/lricardo/miniconda3/lib/python3.5/site-packages/pnnl_atlas-1.0.15-py3.5.egg/atlas/Snakefile -d /home/lricardo/resultados_tiete -p -j 80 --rerun-incomplete --configfile '/home/lricardo/config_tiete.yaml' --nolock --use-conda --config workflow=complete  --' returned non-zero exit status 1

**Comment by brwnj** [comment]
Are you running both indexes for this particular sample? If you're processing this as a single-end sample, you will need to specify that. See https://pnnl-atlas.readthedocs.io/en/latest/assembly/samples.html#single-end-input
