### ISSUE TITLE
Adding deduplication step

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#22]
What do you think of adding a deduplication step. Especially when using a PCR library this could remove bias. In the BBmap suite there is the script [clumpify](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/clumpify-guide/) which also reduces file size of the fastq.gz

**Comment by SilasK** [comment]
@brwnj what do you think of using **clumpify.sh** instead of **Picard MarkDuplicates** to remove PCR duplicates?
clumpify would be at the begining of the pipeline but picard is only after assambly. 



> Clumpify.sh can now mark/remove sequence duplicates (optical/PCR/otherwise) from NGS data

>This does NOT require alignments so it should prove more useful compared to Picard MarkDuplicates. Relevant options for clumpify.sh command are listed below.

>Code:
```
dedupe=f optical=f (default)
Nothing happens with regards to duplicates.

dedupe=t optical=f
All duplicates are detected, whether optical or not.  All copies except one are removed for each duplicate.

dedupe=f optical=t
Nothing happens.

dedupe=t optical=t
````
>Only optical duplicates (those with an X or Y coordinate within dist) are detected.  All copies except one are removed for each duplicate.
The allduplicates flag makes all copies of duplicates removed, rather than leaving a single copy.  But like optical, it has no effect unless dedupe=t.

>Note: If you set "dupedist" to anything greater than 0, "optical" gets enabled automatically.

**Comment by brwnj** [comment]
I see that this is implemented already -- nice work! It's optional and should replace picard MarkDuplicates (which was not removed yet).

**Comment by brwnj** [comment]
`clumpify.sh` is now implemented and Picard's `MarkDuplicates` has been removed.
