### ISSUE TITLE
Issue with databases download

### ISSUE THREAD

**Issue by michoug** [pnnl/atlas#3]
Hi

While running the databases download I run into this error for each of the files to download

Error in job transfer_files while creating output file /data1/Atlas/databases/refseq.tree.
RuleException:
CalledProcessError in line 30 of /home/test/miniconda3/envs/atlas_env/lib/python3.5/site-packages/atlas/rules/download.snakefile:
Command 'curl 'ftp://observers:noVa9lib@ftp.pnl.gov/outgoing/atlas/refseq.tree' -s > /data1/Atlas/databases/refseq.tree' returned non-zero exit status 8
  File "/home/test/miniconda3/envs/atlas_env/lib/python3.5/site-packages/atlas/rules/download.snakefile", line 30, in __rule_transfer_files
  File "/home/test/miniconda3/envs/atlas_env/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Exiting because a job execution failed. Look above for error message

Best
Greg

**Comment by brwnj** [comment]
You can either retry the same command and the workflow will continue to download missing files, or download the files without invoking the `atlas` command by simply doing:

```
curl 'ftp://observers:noVa9lib@ftp.pnl.gov/outgoing/atlas/refseq.tree' -s > /data1/Atlas/databases/refseq.tree
```

**Comment by michoug** [comment]
The command failed again for all the files, I downloaded them manually, thank you
