### ISSUE TITLE
Make normalization optional

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#30]
Normalization how it is implemented now normalizes : 
1. the single end/merged paired-end reads, but takes the unnormed paired end reads into account.
2. the paired end reads but takes the unnormed single end reads into account. 

To me this seems like two biased normalizations.

Megahit shout be able to handle very different abundant metagenomes. Doesn't help for the assembly?Spades has a internal normalization function, so we could use this one instead of bbnorm.

**Comment by brwnj** [comment]
I tested metagenomes and isolate DNA, with and without normalization. Without normalization always assembled more numerous, shorter contigs.
