### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by brwnj** [pnnl/atlas#34]
We need to outline the new features (deduplicate, merge_pairs) that were added and their associated config parameters in the skeleton config generation method as well as the docs for assembly. We've also updated the qc output files a bit and docs should reflect those changes.

**Comment by SilasK** [comment]
@brwnj  Is there a way I can test the development version form github? when I call atlas.py I got an error that the version is undefined.

**Comment by brwnj** [comment]
If you run `python setup.py develop` when making local changes, future `atlas` calls will reflect those changes.

**Comment by brwnj** [comment]
A new issue was created for this.
