### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#49]
@brwnj Cluster support

If I understood it correctly you want to use the environmental variables `SHPFXM` to allow cluster support. 

Currently I'm using cluster scheduler scripts described [here](https://groups.google.com/forum/#!topic/snakemake/7cyqAIfgeq4).

what do you think?

**Comment by SilasK** [comment]
TODO: bbmap scripts use always 15% more than what the java memory requested. We should take this into consideration.

**Comment by brwnj** [comment]
At this point I'm ready to remove those prefixes as I also tend to just use Snakemake's cluster configuration and job submission. The prefix method does work, but I'm pretty sure it isn't universally applicable. At PNNL, we do not share most compute nodes, so the prefix allowed me to reserve a large block of nodes onto which I could submit jobs (using `srun`).

**Comment by brwnj** [comment]
Prefixes removed.
