### ISSUE TITLE
Config file is invalid

### ISSUE THREAD

**Issue by michoug** [pnnl/atlas#5]
Hi,
following the tutorial, I generated the config file and when I try to run the software it tells me that the "The configuration file is invalid."
Greg

[config.txt](https://github.com/pnnl/atlas/files/915591/config.txt)

**Comment by brwnj** [comment]
It may be related to file paths as there was a bug in that part of the code when files were not found. Can you update to 1.0.5 (`pip install -U pnnl-atlas`) and try again.

**Comment by michoug** [comment]
Thank you, it did resolved the issue, which was that 2 databases files were missing
