### ISSUE TITLE
ambigous mapping for coverage calculation

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#51]
To calculate the coverage over features or contigs, there is always the problem of ambiguous reads.
Ideally one should keep all ambiguous positions, where a read maps and then divide the count by the number of ambiguous positions or do some more sophisticated repartition of reads.  

bbmap has the possibility to keep all ambiguous mappings and pileup.sh (from the bbmap package) can count the secondary alignements, but this means a read can be counted multiple times.

@brwnj  Could you send me your original code with samtools. how does it handle the ambiguous reads?

**Comment by brwnj** [comment]
Ambiguous reads are still allowed to map and can be capped using `maximum_counted_map_sites:` in the configuration file. Counts across gene regions are obtained using `featureCounts` with some configurable options. If the user does not want to count multi-mapped reads at all, then they should set `count_multi_mapped_reads: false`. If they only want a single best count for a read then set `primary_only: true`.

The code for these operations is basically unchanged. The only thing we've updated is to use bbwrap to include single and paired-end reads.

**Comment by SilasK** [comment]
Fixed by #63
