### ISSUE TITLE
diamond database

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#52]
Apparently there is still some problems downloading the database. #48 

Fix:

@camel315 It seems that you didn't correctly downloaded the diamond database refseq.dmnd

can you check if is downloaded and that the path in the config file points to the right file?

You can download the database from [here](https://zenodo.org/record/885507). 
But even better is to download the refseq.fasta and to build the database on your own (take some time)

**Comment by camel315** [comment]
Thank you for your prompt reply. I am now using 'atlas download -o ~databases' to download them. Hope this time it will work. What else shall I pay attention to?
In addition, is it possible to include fungi and virus databases into this analysis? I thought is will make full use of the metagenomic sequencing effort for environmental microbiology.
Besides, is it possible to merge the taxonomic table or functional table of different samples together? I tried with atlas version 1.0.17 and get a result, I did not find such a table, probably I am not careful enough.

**Comment by SilasK** [comment]
On what databases did you thought?

No, data is not aggregated between samples. But I'm working on that. I thought to generate make a catalog of all genes identified in any sample, then you can calculate the abundance of these genes in each sample. @brwnj  what do you think?

**Comment by camel315** [comment]
That is will be very convenient for potential users. Another quick question related to the reference database, with the link you listed, there is a bit difference in the md5 number between version 2 and 3 of the 'refseq.dmnd', will it matter when atlas platform uses them?

**Comment by SilasK** [comment]
I think they ae not generated by the same diamond version. 

 

Kind regards

Silas Kieser

**Comment by camel315** [comment]
when I use 'atlas download -o ~database, an error pop up:
![image](https://user-images.githubusercontent.com/9653492/33272365-3b89fd0a-d38a-11e7-9dcb-420d4c0deaf2.png)

**Comment by SilasK** [comment]
Sorry, I don’t know why I doesn’t work but you can download the database manually on the link indicated.

**Comment by camel315** [comment]
Thank you for quick reply. I am doing as suggested, which will take 2.5 hours to download. Hopefully the magic pipeline will work afterwords. Until when can I contact you today if there is any problems pop up?

**Comment by SilasK** [comment]
I will leave the office in one hour but I can check my mails a last time in 2 hours. Which magic do you expect from Atlas? ☺

**Comment by camel315** [comment]
@SilasK Atlas uses one function which combined multiple steps of processing on metagenomic data, that is why I called it magic. For this reason, I would expect it will be popular in the future. I understand that the pipeline is still in development. But for novice like me, I don't know whether and where any error will pop up, therefore, the user may expect prompt feedback. Thank you.

**Comment by SilasK** [comment]
If you have any problems you can test to run atlas assemble with the keywords –until QC_report .wich will run only the QC part (some hours) 

 

Kidn regards

Silas

**Comment by camel315** [comment]
@SilasK, Following the examples 'atlas assemble –until QC_report config.yaml', is it possible to run a certain steps, e.g.  from QC_report to error_correction?

**Comment by brwnj** [comment]
The "onerror" rule was not updated to the correct Zenodo file archive. I've fixed this bug and pushed the changes. The error you're seeing above occurs when the md5 does not match the expected and as you downloaded from file archive 885507, its md5 is seen as wrong.

**Comment by SilasK** [comment]
@camel315  the `--until  target` is a [snakemake keyword](http://snakemake.readthedocs.io/en/stable/executable.html) which can be added to the atlas command. But you should use it  `atlas assemble config.yaml  –until QC_report` as described in the [docs](http://pnnl-atlas.readthedocs.io/en/latest/setup/snakemake.html?highlight=snakemake). 

as target you can take any rule name defined in the assembly.snakefile. 
But keep in mind that error correction is only an intermediate state before assembly so you want better use `--until run_megahit`or `--until run_spades`.

**Comment by camel315** [comment]
@SilasK Sorry to disturb you again. I have re-installed packages from conda then on. It stopped running when rule read_stats, probably due to a CalledProcessError in line 126 of atlas/rules/assemble.snakefile. Could you please help me to figure it out? Thank you.
![image](https://user-images.githubusercontent.com/9653492/33310022-84809e38-d420-11e7-9c21-51488ab32550.png)

**Comment by SilasK** [comment]
Good morning.  

 

Can you look in the log file? 

I assume atlas doesn’t find the “reformat.sh” executable. Can you test this? If it is not found could you install it via “conda install bbmap -c bioconda”.

 

 

PS: Could you try to copy paste the error message instead of an image if it doesn’t take too much time. So other people can search for the text.

**Comment by camel315** [comment]
@SilasK 
I think reformat.sh is working because:
/home/syang/anaconda3/bin/reformat.sh

Written by Brian Bushnell
Last modified April 10, 2017

Description:  Reformats reads to change ASCII quality encoding, interleaving, file format, or compression format.
Optionally performs additional functions such as quality trimming, subsetting, and subsampling.
Supports fastq, fasta, fasta+qual, scarf, oneline, sam, bam, gzip, bz2.

Usage:  reformat.sh in=<file> in2=<file2> out=<outfile> out2=<outfile2>

in2 and out2 are for paired reads and are optional.
If input is paired and there is only one output file, it will be written interleaved.

For the log file:

cat OD3/logs/read_stats.log
Unspecified format for input in1; defaulting to fastq.
Exception in thread "main" java.lang.RuntimeException: Can't find file in1
        at fileIO.ReadWrite.getRawInputStream(ReadWrite.java:865)
        at fileIO.ReadWrite.getInputStream(ReadWrite.java:830)
        at fileIO.FileFormat.getFirstOctet(FileFormat.java:406)
        at stream.FASTQ.isInterleaved(FASTQ.java:126)
        at stream.FastqReadInputStream.<init>(FastqReadInputStream.java:60)
        at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:119)
        at stream.ConcurrentReadInputStream.getReadInputStream(ConcurrentReadInputStream.java:45)
        at jgi.MakeLengthHistogram.calc(MakeLengthHistogram.java:104)
        at jgi.MakeLengthHistogram.main(MakeLengthHistogram.java:91)

**Comment by SilasK** [comment]
Hopla, I saw the error.

 

readlength.sh in=in1=file  should be readlength.sh in=file

 

either you copy this in the anaconda/path/to/atlas/rules/assembly.snakefile already installed. Or you get the newest version from github. 

 

Git clone https://github.com/pnnl/atlas.git

cd atlas

 

python setup.py install develop

**Comment by camel315** [comment]
@SilasK  I met another error to disturb you, please see the error file:
[err.txt](https://github.com/pnnl/atlas/files/1510141/err.txt)
In addition, what shall I do if I want to include reference database of virus (e.g. MvirDB for resitance screening), Protozoa and fungi? Are there any documentation from Atlas to fillfull that? To include these reference database, does the program scripts of atlas should also be accordingly modified?
Thank you

**Comment by SilasK** [comment]
I'm sorry I don't know. Do you have an internet connection? 
@brwnj may be you can answer the question how to include other databases. I think it would be good to have a log file in the checkm_init script, which is not removed on error.

**Comment by brwnj** [comment]
The reformat bug was fixed in e9ed5ab1287f7d6a80693c2df60dafe0910742e8. Please start a new issue when changing topics so we can better track issues and requests.
