### ISSUE TITLE
Preprocessing sequences

### ISSUE THREAD

**Issue by brwnj** [pnnl/atlas#55]
In the configuration we added:

```
conf["assembly_preprocessing_steps"]=['normalized', 'errorcorr', 'merged']
```

This gives the impression that these steps are optional or that their order can be changed. They are currently required steps of preprocessing and occur linearly starting with normalization.

**Comment by SilasK** [comment]
Yes, I tried to implement the steps quite general, to refuse them may be somewhere else. The steps are in fact optional and the order can be changed. But I see this is not really necessary. So I might go back to the 'merge pairs'

To be clear there normalization, error correction, and merging is done on the qc reads just before assembly. 

In contrast to earlier, the reads mapped to the prefilterd contigs are not error corrected with tadpole, nor merged. 

I thought this could allow SNP calling later on.
