### ISSUE TITLE
Slim conda environment files

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#56]
@brwnj I'm implementing concoct, therefore I created the env file with `conde env export > concoct.yaml`. 

When I compare [my file](https://github.com/pnnl/atlas/blob/gene_catalog/atlas/envs/concoct.yaml) [with yours](https://github.com/pnnl/atlas/blob/gene_catalog/atlas/envs/optional_genome_binning.yaml) I think you used another way to generate them. which makes them simpler?

**Comment by brwnj** [comment]
I determine the primary requirements and depend on the bioconda recipes to add the minutiae. Yours will likely work though I would remove name and prefix definitions.
