### ISSUE TITLE
Init error

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#61]
when starting the pipeline and the samples declared in the config file are not found a specific error should be given instead of the default snakemeke error

**Comment by camel315** [comment]
@SilasK How to specifically give instead of using default setting? Could you please also have a look at https://github.com/pnnl/atlas/issues/58, do you mean the same thing? Thank you.

**Comment by brwnj** [comment]
Added in ae8d58a1840d4c687c277dff8c7e73388bd7a0d0.
