### ISSUE TITLE
Initalise conda envs in download

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#68]
We should cycle trough the env and install them in the download command which is called from a server with internet. Then atlas can be run without internet connection I think.

**Comment by brwnj** [comment]
Proper usage in this case already exists within snakemake. Say your command was:

    atlas assemble --jobs 24 --out-dir results config.yaml

You append the snakemake args for creating the environments only:

    atlas assemble --jobs 24 --out-dir results config.yaml --create-envs-only
