### ISSUE TITLE
Make java_mem_min config option

### ISSUE THREAD

**Issue by jmtsuji** [pnnl/atlas#79]
**Background**

Currently, ATLAS has a `java_mem` setting in the configuration (.yaml) file that allows users to specify the memory allowance of tools running using java (e.g., most BBTools programs). This appears to control the `-Xmx` flag in java for the max. allowed memory.

I am running ATLAS on a server with a ZFS ARC cache. Our ARC cache allows up to half of our system's RAM to be used to store files for faster read/write speed. Upon memory pressure, the ARC cache will automatically scale down to allow programs to utilize more RAM.

**Problem description**

ATLAS fails when first initializing various BBTools programs due to a memory mapping error, e.g.,

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 71583137792 bytes for committing reserved memory.
```

I think this is because, although the RAM is available on our server, it is currently occupied by the ARC cache. The ARC cache would shrink if given the chance, but the BBTools program fails immediately.

**Proposed solution**

By only setting the `-Xmx` flag for most BBTools, the program requires that the max. RAM be completely available when the program first initializes. I propose also setting the `-Xms` flag to give the minimum required memory for the program to initialize. This should alleviate any problems interacting with our ARC cache.

To do so, the `java_mem` parameter in the config (.yaml) file would need to be split into `java_mem_min` and `java_mem_max`. Then, both settings could be called for each BBTool. For example `rule_deduplicate` could be changed as follows (last portion of rule shown):

Current:
```
        resources:
            mem = config.get("java_mem", JAVA_MEM)
        shell:
            """
            clumpify.sh \
                {params.inputs} \
                {params.outputs} \
                overwrite=true\
                dedupe=t \
                dupesubs={params.dupesubs} \
                optical={params.only_optical}\
                threads={threads} \
                -Xmx{resources.mem}G 2> {log}
            """
```

Updated
```
        resources:
            mem_min = config.get("java_mem_min", JAVA_MEM_MIN)
            mem_max = config.get("java_mem_max", JAVA_MEM_MAX)
        shell:
            """
            clumpify.sh \
                {params.inputs} \
                {params.outputs} \
                overwrite=true\
                dedupe=t \
                dupesubs={params.dupesubs} \
                optical={params.only_optical}\
                threads={threads} \
                -Xms{resources.mem_min}G \
                -Xmx{resources.mem_max}G 2> {log}
            """
```

Does this seem like a reasonable change? If so, I'd be willing to start a branch with the updates.

Thanks for all your work on this tool.

**Comment by SilasK** [comment]
I read that all bbtools need in addition to the -Xmx required memory 15% of overhead. 
I therefore adapted the rules in #77 to pass less memory to java than to the server. 
So you think tis would also solve your problem?

**Comment by jmtsuji** [comment]
Interesting. I'll test this and will let you know.

**Comment by jmtsuji** [comment]
After some initial testing, the issue appears to be gone with the latest version of ATLAS. Maybe it was indeed a different type of memory allocation issue and did not have to do with interactions with the ARC cache. I'll close this issue for now and will re-open if anything comes up.

**Comment by MgLaMontagne** [comment]
I ran "atlas run qc on" a laptop with 16 GB or RAM and I receive the same error message as above:
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 54760833024 bytes ...

I changed the config.yaml file to  managed to get through the qc on a subset of my data. Is there a chance I can execute "atlas run all" on a laptop? 
# threads and memory (GB) for most jobs especially from BBtools...
threads: 8
mem: 15
